# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'watir-webdriver'
require 'page-object'

Kernel.puts 'Starting browser...'
browser = Watir::Browser.new :firefox

Before do
  @browser = browser
end

After do
  if @browser.text.include? 'Sign out'
  @browser.link(:text, 'Sign out').click
  end
end

at_exit do
  @browser.close
end


